M48
; DRILL file {KiCad (6.0.1)} date Sun Jan 30 09:16:29 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-30T09:16:29+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1693
%
G90
G05
T1
X2.24Y-2.74
T2
X2.1Y-1.6
X2.1Y-3.86
X5.86Y-1.6
X5.86Y-3.86
T0
M30
